# Generated by Django 3.2.2 on 2021-06-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitshopapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitmodel',
            name='desc',
            field=models.CharField(max_length=300),
        ),
    ]
